name: node-env
channels:
  - knime
  - conda-forge
dependencies:
  - knime-extension
  - knime-python-base
  - python=3.11
  - pip:
      - google-api-python-client==2.186.0
      - google-auth-oauthlib==1.2.3
      - psutil==7.1.3
      - requests==2.32.5
