name: node-env
channels:
  - knime
  - conda-forge
  - defaults
dependencies:
  - knime-extension
  - knime-python-base
  - python=3.11
  - pip:
      - google-api-python-client==2.161.0
      - google-auth-oauthlib==1.2.1
